apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
        - name: mern-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
